export const pdfTranslations: Record<string, Record<string, string>> = {
  en: {
    reportTitle: "Marriage Matching Report",
    horoTitle: "Astrology Engine",
    vivahamitra: "<span style='color:#b4366f'>Vivaha</span><span style='color:#2196f3'>mitra</span>",
    name: "Name",
    gender: "Gender",
    gotram: "Gotram",
    dob: "Date of Birth",
    tob: "Time of Birth",
    pob: "Place of Birth",
    latlon: "Longitude & Latitude",
    timezone: "Time Zone",
    ayanamsa: "Ayanamsa",
    nakshatraPada: "Janma Nakshatra - Pada",
    rasiLord: "Janma Rasi - Rasi Adhipati",
    lagnaLord: "Lagna - Lagna Adhipati",
    tithi: "Tithi",
    planetTable: "Planetary Positions (Deg. Min. Sec.)",
    graha: "Planet",
    rasi: "Rasi",
    long: "Longitude",
    nakPada: "Nakshatra/Pada",
    rasiChart: "Rasi Chart",
    navamsaChart: "Navamsa Chart",
    bhavaChart: "Bhava Chart",
    dasaSesham: "Janmakala Dasa Sesham =",
    dasaTitle: "Dasha Periods",
    dasaStart: "Start Date",
    dasaEnd: "End Date",
    bhukti: "Bhukti",
    dasa: "Dasha",
    groom: "Groom",
    bride: "Bride",
    overallScore: "Overall Compatibility Score",
    matchPercentage: "Match Percentage",
    executiveSummary: "Executive Summary",
    groomHoroscopeDetails: "Groom Horoscope Details",
    brideHoroscopeDetails: "Bride Horoscope Details",
    ashtaKootaMatching: "Ashta Koota Matching",
    koota: "Koota",
    maxPoints: "Max Points",
    obtained: "Obtained",
    description: "Description",
    total: "TOTAL",
    dashavidhaPorutham: "Dashavidha Porutham (South Indian)",
    porutham: "Porutham",
    status: "Status",
    meaning: "Meaning",
    doshaAnalysis: "Dosha Analysis",
    groomDoshas: "Groom Doshas",
    brideDoshas: "Bride Doshas",
    noDoshas: "No major doshas detected.",
    manglikConflict: "Manglik (Kuja) Dosha Conflict",
    conflictPresent: "Conflict Present",
    yes: "Yes",
    no: "No",
    statusLabel: "Status",
    cancelled: "Cancelled/Neutralized",
    active: "Active",
    paapaSamyam: "Paapa Samyam (Dosha Samyam)",
    groomPoints: "Groom Points",
    bridePoints: "Bride Points",
    totalPoints: "Total Points",
    thematicCompatibility: "Thematic Compatibility",
    children: "Children & Progeny",
    health: "Health & Well-being",
    finance: "Finance & Prosperity",
    longevity: "Longevity",
    finalConclusion: "Final Conclusion",
    recommendation: "Recommendation",
    strengths: "Strengths",
    warnings: "Warnings",
    mandatoryFailures: "Mandatory Failures / Severe Doshas",
    expertNotes: "Expert Review Notes",
    average: "Average"
  },
  te: {
    reportTitle: "వివాహ పొంతన నివేదిక",
    horoTitle: "ఆస్ట్రాలజీ ఇంజిన్",
    vivahamitra: "<span style='color:#b4366f'>వివాహ</span><span style='color:#2196f3'>మిత్ర</span>",
    name: "పేరు",
    gender: "లింగము",
    gotram: "గోత్రము",
    dob: "జన్మ దినము",
    tob: "పుట్టిన సమయము",
    pob: "జన్మ స్థానము",
    latlon: "రేఖాంశము & అక్షాంశము",
    timezone: "కాలమండలము",
    ayanamsa: "అయనాంశము",
    nakshatraPada: "జన్మ నక్షత్రము - పాదము",
    rasiLord: "జన్మ రాశి - రాశి అధిపతి",
    lagnaLord: "లగ్నము (ఉచ్ఛ) - లగ్న అధిపతి",
    tithi: "తిథి",
    planetTable: "గ్రహ స్థితులు (డిగ్రీ. నిమిషము. సెకండు.)",
    graha: "గ్రహము",
    rasi: "రాశి",
    long: "రేఖాంశము",
    nakPada: "నక్షత్రము/పాదము",
    rasiChart: "రాశి చక్రం",
    navamsaChart: "నవాంశము",
    bhavaChart: "భావ చార్ట్",
    dasaSesham: "జననకాల దశా శేషము =",
    dasaTitle: "దశాకాల మార్పులు",
    dasaStart: "ప్రారంభము",
    dasaEnd: "అంత్యము",
    bhukti: "భుక్తి",
    dasa: "దశ",
    groom: "వరుడు",
    bride: "వధువు",
    overallScore: "మొత్తం పొంతన స్కోరు",
    matchPercentage: "పొంతన శాతం",
    executiveSummary: "కార్యనిర్వాహక సారాంశం",
    groomHoroscopeDetails: "వరుని జాతక వివరాలు",
    brideHoroscopeDetails: "వధువు జాతక వివరాలు",
    ashtaKootaMatching: "అష్ట కూట పొంతన",
    koota: "కూట",
    maxPoints: "గరిష్ట పాయింట్లు",
    obtained: "పొందినవి",
    description: "వివరణ",
    total: "మొత్తం",
    dashavidhaPorutham: "దశవిధ పొంతన (దక్షిణ భారత)",
    porutham: "పొంతన",
    status: "స్థితి",
    meaning: "అర్థం",
    doshaAnalysis: "దోష విశ్లేషణ",
    groomDoshas: "వరుని దోషాలు",
    brideDoshas: "వధువు దోషాలు",
    noDoshas: "ప్రధాన దోషాలు లేవు.",
    manglikConflict: "కుజ దోషం",
    conflictPresent: "సంఘర్షణ ఉందా",
    yes: "అవును",
    no: "కాదు",
    statusLabel: "స్థితి",
    cancelled: "రద్దు చేయబడింది",
    active: "క్రియాశీల",
    paapaSamyam: "దోష సామ్యం (పాప సామ్యం)",
    groomPoints: "వరుని పాయింట్లు",
    bridePoints: "వధువు పాయింట్లు",
    totalPoints: "మొత్తం పాయింట్లు",
    thematicCompatibility: "అంశాల వారీగా పొంతన",
    children: "సంతానం",
    health: "ఆరోగ్యం",
    finance: "ఆర్థిక స్థితి",
    longevity: "ఆయుష్షు",
    finalConclusion: "తుది నిర్ణయం",
    recommendation: "సిఫార్సు",
    strengths: "బలాలు",
    warnings: "హెచ్చరికలు",
    mandatoryFailures: "తప్పనిసరి వైఫల్యాలు",
    expertNotes: "నిపుణుల సమీక్ష",
    average: "సాధారణం"
  },
  hi: {
    reportTitle: "विवाह मिलान रिपोर्ट",
    horoTitle: "ज्योतिष इंजन",
    vivahamitra: "<span style='color:#b4366f'>विवाह</span><span style='color:#2196f3'>मित्र</span>",
    name: "नाम",
    gender: "लिंग",
    gotram: "गोत्र",
    dob: "जन्म तिथि",
    tob: "जन्म समय",
    pob: "जन्म स्थान",
    latlon: "देशांतर और अक्षांश",
    timezone: "समय क्षेत्र",
    ayanamsa: "अयनांश",
    nakshatraPada: "जन्म नक्षत्र - पद",
    rasiLord: "जन्म राशि - राशि स्वामी",
    lagnaLord: "लग्न - लग्न स्वामी",
    tithi: "तिथि",
    planetTable: "ग्रह स्थिति",
    graha: "ग्रह",
    rasi: "राशि",
    long: "देशांतर",
    nakPada: "नक्षत्र/पद",
    rasiChart: "राशि चक्र",
    navamsaChart: "नवांश चक्र",
    bhavaChart: "भाव चक्र",
    dasaSesham: "जन्मकाल दशा शेष =",
    dasaTitle: "दशा काल",
    dasaStart: "प्रारंभ तिथि",
    dasaEnd: "अंतिम तिथि",
    bhukti: "भुक्ति",
    dasa: "दशा",
    groom: "वर",
    bride: "वधू",
    overallScore: "कुल मिलान स्कोर",
    matchPercentage: "मिलान प्रतिशत",
    executiveSummary: "कार्यकारी सारांश",
    groomHoroscopeDetails: "वर की कुंडली का विवरण",
    brideHoroscopeDetails: "वधू की कुंडली का विवरण",
    ashtaKootaMatching: "अष्ट कूट मिलान",
    koota: "कूट",
    maxPoints: "अधिकतम अंक",
    obtained: "प्राप्त अंक",
    description: "विवरण",
    total: "कुल",
    dashavidhaPorutham: "दशविध पोरुथम (दक्षिण भारतीय)",
    porutham: "पोरुथम",
    status: "स्थिति",
    meaning: "अर्थ",
    doshaAnalysis: "दोष विश्लेषण",
    groomDoshas: "वर के दोष",
    brideDoshas: "वधू के दोष",
    noDoshas: "कोई प्रमुख दोष नहीं।",
    manglikConflict: "मांगलिक (कुज) दोष संघर्ष",
    conflictPresent: "संघर्ष मौजूद",
    yes: "हाँ",
    no: "नहीं",
    statusLabel: "स्थिति",
    cancelled: "रद्द / निष्प्रभावी",
    active: "सक्रिय",
    paapaSamyam: "दोष साम्यम (पाप साम्यम)",
    groomPoints: "वर के अंक",
    bridePoints: "वधू के अंक",
    totalPoints: "कुल अंक",
    thematicCompatibility: "विषयगत अनुकूलता",
    children: "संतान",
    health: "स्वास्थ्य",
    finance: "धन और समृद्धि",
    longevity: "आयु",
    finalConclusion: "अंतिम निष्कर्ष",
    recommendation: "सिफारिश",
    strengths: "शक्तियां",
    warnings: "चेतावनियाँ",
    mandatoryFailures: "अनिवार्य विफलताएं / गंभीर दोष",
    expertNotes: "विशेषज्ञ समीक्षा",
    average: "औसत"
  },
  ta: {
    reportTitle: "திருமண பொருத்தம் அறிக்கை",
    horoTitle: "ஜோதிட இயந்திரம்",
    vivahamitra: "<span style='color:#b4366f'>விவாஹ</span><span style='color:#2196f3'>மித்ரா</span>",
    name: "பெயர்",
    gender: "பாலினம்",
    gotram: "கோத்திரம்",
    dob: "பிறந்த தேதி",
    tob: "பிறந்த நேரம்",
    pob: "பிறந்த இடம்",
    latlon: "தீர்க்கரேகை & அட்சரேகை",
    timezone: "நேர மண்டலம்",
    ayanamsa: "அயனாம்சம்",
    nakshatraPada: "ஜென்ம நட்சத்திரம் - பாதம்",
    rasiLord: "ஜென்ம ராசி - ராசி அதிபதி",
    lagnaLord: "லக்னம் - லக்ன அதிபதி",
    tithi: "திதி",
    planetTable: "கிரக நிலைகள்",
    graha: "கிரகம்",
    rasi: "ராசி",
    long: "தீர்க்கரேகை",
    nakPada: "நட்சத்திரம்/பாதம்",
    rasiChart: "ராசி சக்கரம்",
    navamsaChart: "நவாம்சம்",
    bhavaChart: "பாவ சக்கரம்",
    dasaSesham: "ஜனனகால தசா இருப்பு =",
    dasaTitle: "தசா காலங்கள்",
    dasaStart: "தொடக்க தேதி",
    dasaEnd: "முடிவு தேதி",
    bhukti: "புக்தி",
    dasa: "தசை",
    groom: "மணமகன்",
    bride: "மணமகள்",
    overallScore: "ஒட்டுமொத்த பொருத்தம்",
    matchPercentage: "பொருத்தம் சதவீதம்",
    executiveSummary: "நிர்வாக சுருக்கம்",
    groomHoroscopeDetails: "மணமகன் ஜாதக விவரங்கள்",
    brideHoroscopeDetails: "மணமகள் ஜாதக விவரங்கள்",
    ashtaKootaMatching: "அஷ்ட கூட பொருத்தம்",
    koota: "கூடம்",
    maxPoints: "அதிகபட்ச புள்ளிகள்",
    obtained: "பெறப்பட்டவை",
    description: "விளக்கம்",
    total: "மொத்தம்",
    dashavidhaPorutham: "தசவித பொருத்தம்",
    porutham: "பொருத்தம்",
    status: "நிலை",
    meaning: "அர்த்தம்",
    doshaAnalysis: "தோஷ பகுப்பாய்வு",
    groomDoshas: "மணமகன் தோஷங்கள்",
    brideDoshas: "மணமகள் தோஷங்கள்",
    noDoshas: "பெரிய தோஷங்கள் இல்லை.",
    manglikConflict: "செவ்வாய் தோஷம்",
    conflictPresent: "மோதல் உள்ளதா",
    yes: "ஆம்",
    no: "இல்லை",
    statusLabel: "நிலை",
    cancelled: "ரத்து செய்யப்பட்டது",
    active: "செயலில் உள்ளது",
    paapaSamyam: "தோஷ சாம்யம் (பாப சாம்யம்)",
    groomPoints: "மணமகன் புள்ளிகள்",
    bridePoints: "மணமகள் புள்ளிகள்",
    totalPoints: "மொத்த புள்ளிகள்",
    thematicCompatibility: "கருப்பொருள் பொருத்தம்",
    children: "குழந்தை பாக்கியம்",
    health: "ஆரோக்கியம்",
    finance: "நிதி நிலை",
    longevity: "ஆயுள்",
    finalConclusion: "இறுதி முடிவு",
    recommendation: "பரிந்துரை",
    strengths: "பலங்கள்",
    warnings: "எச்சரிக்கைகள்",
    mandatoryFailures: "கட்டாய தோல்விகள்",
    expertNotes: "நிபுணர் ஆய்வு",
    average: "சராசரி"
  },
  kn: {
    reportTitle: "ವಿವಾಹ ಹೊಂದಾಣಿಕೆ ವರದಿ",
    horoTitle: "ಜ್ಯೋತಿಷ್ಯ ಎಂಜಿನ್",
    vivahamitra: "<span style='color:#b4366f'>ವಿವಾಹ</span><span style='color:#2196f3'>ಮಿತ್ರ</span>",
    name: "ಹೆಸರು",
    gender: "ಲಿಂಗ",
    gotram: "ಗೋತ್ರ",
    dob: "ಹುಟ್ಟಿದ ದಿನಾಂಕ",
    tob: "ಹುಟ್ಟಿದ ಸಮಯ",
    pob: "ಹುಟ್ಟಿದ ಸ್ಥಳ",
    latlon: "ರೇಖಾಂಶ ಮತ್ತು ಅಕ್ಷಾಂಶ",
    timezone: "ಸಮಯ ವಲಯ",
    ayanamsa: "ಅಯನಾಂಶ",
    nakshatraPada: "ಜನ್ಮ ನಕ್ಷತ್ರ - ಪಾದ",
    rasiLord: "ಜನ್ಮ ರಾಶಿ - ರಾಶಿ ಅಧಿಪತಿ",
    lagnaLord: "ಲಗ್ನ - ಲಗ್ನ ಅಧಿಪತಿ",
    tithi: "ತಿಥಿ",
    planetTable: "ಗ್ರಹಗಳ ಸ್ಥಾನಗಳು",
    graha: "ಗ್ರಹ",
    rasi: "ರಾಶಿ",
    long: "ರೇಖಾಂಶ",
    nakPada: "ನಕ್ಷತ್ರ/ಪಾದ",
    rasiChart: "ರಾಶಿ ಚಕ್ರ",
    navamsaChart: "ನವಾಂಶ ಚಕ್ರ",
    bhavaChart: "ಭಾವ ಚಕ್ರ",
    dasaSesham: "ಜನನಕಾಲ ದಶಾ ಶೇಷ =",
    dasaTitle: "ದಶಾ ಅವಧಿಗಳು",
    dasaStart: "ಪ್ರಾರಂಭ ದಿನಾಂಕ",
    dasaEnd: "ಮುಕ್ತಾಯ ದಿನಾಂಕ",
    bhukti: "ಭುಕ್ತಿ",
    dasa: "ದಶ",
    groom: "ವರ",
    bride: "ವಧು",
    overallScore: "ಒಟ್ಟಾರೆ ಹೊಂದಾಣಿಕೆ",
    matchPercentage: "ಹೊಂದಾಣಿಕೆ ಶೇಕಡಾವಾರು",
    executiveSummary: "ಕಾರ್ಯಕಾರಿ ಸಾರಾಂಶ",
    groomHoroscopeDetails: "ವರನ ಜಾತಕ ವಿವರಗಳು",
    brideHoroscopeDetails: "ವಧುವಿನ ಜಾತಕ ವಿವರಗಳು",
    ashtaKootaMatching: "ಅಷ್ಟ ಕೂಟ ಹೊಂದಾಣಿಕೆ",
    koota: "ಕೂಟ",
    maxPoints: "ಗರಿಷ್ಠ ಅಂಕಗಳು",
    obtained: "ಪಡೆದ ಅಂಕಗಳು",
    description: "ವಿವರಣೆ",
    total: "ಒಟ್ಟು",
    dashavidhaPorutham: "ದಶವಿಧ ಪೊರುತಮ್",
    porutham: "ಪೊರುತಮ್",
    status: "ಸ್ಥಿತಿ",
    meaning: "ಅರ್ಥ",
    doshaAnalysis: "ದೋಷ ವಿಶ್ಲೇಷಣೆ",
    groomDoshas: "ವರನ ದೋಷಗಳು",
    brideDoshas: "ವಧುವಿನ ದೋಷಗಳು",
    noDoshas: "ಯಾವುದೇ ಪ್ರಮುಖ ದೋಷಗಳಿಲ್ಲ.",
    manglikConflict: "ಮಂಗಳ ದೋಷ",
    conflictPresent: "ಸಂಘರ್ಷ ಇದೆಯೇ",
    yes: "ಹೌದು",
    no: "ಇಲ್ಲ",
    statusLabel: "ಸ್ಥಿತಿ",
    cancelled: "ರದ್ದುಗೊಳಿಸಲಾಗಿದೆ",
    active: "ಸಕ್ರಿಯ",
    paapaSamyam: "ದೋಷ ಸಾಮ್ಯಂ (ಪಾಪ ಸಾಮ್ಯಂ)",
    groomPoints: "ವರನ ಅಂಕಗಳು",
    bridePoints: "ವಧುವಿನ ಅಂಕಗಳು",
    totalPoints: "ಒಟ್ಟು ಅಂಕಗಳು",
    thematicCompatibility: "ವಿಷಯಾಧಾರಿತ ಹೊಂದಾಣಿಕೆ",
    children: "ಸಂತಾನ",
    health: "ಆರೋಗ್ಯ",
    finance: "ಹಣಕಾಸು",
    longevity: "ಆಯುಷ್ಯ",
    finalConclusion: "ಅಂತಿಮ ತೀರ್ಮಾನ",
    recommendation: "ಶಿಫಾರಸು",
    strengths: "ಸಾಮರ್ಥ್ಯಗಳು",
    warnings: "ಎಚ್ಚರಿಕೆಗಳು",
    mandatoryFailures: "ಕಡ್ಡಾಯ ವೈಫಲ್ಯಗಳು",
    expertNotes: "ತಜ್ಞರ ವಿಮರ್ಶೆ",
    average: "ಸಾಧಾರಣ"
  }
};
