import puppeteer from 'puppeteer';

import { AstrologyEngine } from '../astrology/engine/AstrologyEngine';
import { BrowserManager } from './browserManager';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';
import { HoroscopeV2ResponseData, HoroscopeV2Chart } from '../types/horoscopeV2';
import { LocalizationEngine } from './LocalizationEngine';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const zodiacCache: Record<number, string> = {};
let zodiacCacheLoaded = false;
function getZodiacIcon(i: number): string {
  if (!zodiacCacheLoaded) {
    for (let j = 1; j <= 12; j++) {
      try {
        const imgPath = path.join(process.cwd(), 'public', 'zodiac', `${j}.webp`);
        if (fs.existsSync(imgPath)) {
          zodiacCache[j] = `<img src="data:image/webp;base64,${fs.readFileSync(imgPath, 'base64')}" alt="Rasi ${j}" />`;
        } else {
          zodiacCache[j] = '';
        }
      } catch (e) {
        zodiacCache[j] = '';
      }
    }
    zodiacCacheLoaded = true;
  }
  return zodiacCache[i] || '';
}

export class PdfService {
  /**
   * Generates a PDF report from the canonical horoscope data and returns a base64 string.
   */
  public static async generateHoroscopePdf(data: HoroscopeV2ResponseData, lang: string = 'en'): Promise<{ base64: string, fileName: string }> {
    const timestamp = Date.now();
    const fileName = `horoscope-${data.birthDetails.name.replace(/\s+/g, '_').toLowerCase()}-${timestamp}.pdf`;

    const htmlContent = this.buildHtmlTemplate(data, lang);

    const getDisclaimerText = (l: string) => {
      switch (l) {
        case 'te': return 'గమనిక: ఈ నివేదిక తార్కిక నియమాల ద్వారా రూపొందించబడింది, దయచేసి బలమైన జ్యోతిషశాస్త్ర సలహా తీసుకోండి.';
        case 'ta': return 'குறிப்பு: இந்த அறிக்கை தர்க்கரீதியான விதிகளால் உருவாக்கப்பட்டது, தயவுசெய்து வலுவான ஜோதிட ஆலோசனையைப் பெறவும்.';
        case 'hi': return 'नोट: यह रिपोर्ट तार्किक नियमों द्वारा उत्पन्न की गई है, कृपया मजबूत ज्योतिषीय सलाह लें।';
        case 'kn': return 'ಸೂಚನೆ: ಈ ವರದಿಯನ್ನು ತಾರ್ಕಿಕ ನಿಯಮಗಳಿಂದ ರಚಿಸಲಾಗಿದೆ, ದಯವಿಟ್ಟು ಬಲವಾದ ಜ್ಯೋತಿಷ್ಯ ಸಲಹೆಯನ್ನು ಪಡೆಯಿರಿ.';
        default: return 'NOTE: The report was generated by logical rules, please take strong astrological advice.';
      }
    };

    const browser = await BrowserManager.getBrowser();
    const page = await browser.newPage();

    // Set content and wait for web fonts to load
    await page.setContent(htmlContent, { waitUntil: 'load' });

    const pdfBuffer = await page.pdf({
      format: 'A4',
      printBackground: true,
      displayHeaderFooter: true,
      headerTemplate: '<span></span>',
      footerTemplate: `
        <div style="width: 100%; display: flex; flex-direction: column; font-family: sans-serif; padding: 0 15mm; padding-bottom: 5px;">
           <div style="text-align: center; font-size: 8px; color: #888; margin-bottom: 4px; font-style: italic;">
             ${getDisclaimerText(lang)}
           </div>
           <div style="display: flex; justify-content: space-between; align-items: center; font-size: 10px; color: #555;">
             <span style="font-weight: bold; font-size: 12px;">
                www.<span style="color: #b4366f;">vivaha</span><span style="color: #2196f3;">mitra</span>.in
             </span>
             <span>Generated On: ${new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })}</span>
           </div>
        </div>
      `,
      margin: {
        top: '20mm',
        right: '15mm',
        bottom: '25mm',
        left: '15mm'
      }
    });

    await page.close();

    // We cast Buffer to string to satisfy older type definitions if any, though puppeteer returns Uint8Array in newer versions
    const bufferData = Buffer.isBuffer(pdfBuffer) ? pdfBuffer : Buffer.from(pdfBuffer);
    const base64 = bufferData.toString('base64');

    return { base64, fileName };
  }

  private static buildHtmlTemplate(data: HoroscopeV2ResponseData, lang: string): string {
    // We construct the HTML to visually match the reference layout.
    // For this implementation, we use English labels since the JSON is language-neutral,
    // but we embed Unicode fonts to support multi-lang rendering if requested.

    const isTe = lang === 'te';

    // Base64 encode logo for watermark
    const logoPath = path.join(__dirname, '..', '..', 'api', 'logo.png');
    let logoDataUri = "";
    if (fs.existsSync(logoPath)) {
      const logoBase64 = fs.readFileSync(logoPath).toString('base64');
      logoDataUri = `data:image/png;base64,${logoBase64}`;
    }

    const langCode = ["en", "te", "hi", "ta", "kn"].includes(lang) ? lang : "en";
    const loc = LocalizationEngine.getInstance();
    const L: Record<string, string> = {};
    const pdfKeys = ["reportTitle", "horoTitle", "vivahamitra", "name", "gender", "gotram", "dob", "tob", "pob", "latlon", "timezone", "ayanamsa", "nakshatraPada", "rasiLord", "lagnaLord", "tithi", "planetTable", "graha", "rasi", "long", "nakPada", "rasiChart", "navamsaChart", "bhavaChart", "dasaSesham", "dasaTitle", "dasaStart", "dasaEnd", "bhukti", "dasa", "groom", "bride", "overallScore", "matchPercentage", "executiveSummary", "groomHoroscopeDetails", "brideHoroscopeDetails", "ashtaKootaMatching", "koota", "maxPoints", "obtained", "description", "total", "dashavidhaPorutham", "porutham", "status", "meaning", "doshaAnalysis", "groomDoshas", "brideDoshas", "noDoshas", "manglikConflict", "conflictPresent", "yes", "no", "statusLabel", "cancelled", "active", "paapaSamyam", "groomPoints", "bridePoints", "totalPoints", "thematicCompatibility", "children", "health", "finance", "longevity", "finalConclusion", "recommendation", "strengths", "warnings", "mandatoryFailures", "expertNotes", "average", "sunrise", "sunset", "yoga", "karana", "vara"];
    pdfKeys.forEach(k => { L[k] = loc.get(`PDF.${k.toUpperCase()}`, langCode); });

    const glKeys = [
      "GLOSSARY_TITLE", "GLOSSARY_DESC", "TITHI_TITLE", "TITHI_DESC",
      "VARA_TITLE", "VARA_DESC", "NAKSHATRA_TITLE", "NAKSHATRA_DESC",
      "YOGA_TITLE", "YOGA_DESC", "KARANA_TITLE", "KARANA_DESC",
      "LAGNA_TITLE", "LAGNA_DESC", "RASI_TITLE", "RASI_DESC"
    ];
    glKeys.forEach(k => { L[k] = loc.get(`GLOSSARY.${k}`, langCode); });

    const howToKeys = [
      "TITLE", "SUBTITLE", "SECTION1_TITLE", "SECTION1_DESC",
      "SECTION2_TITLE", "SECTION2_DESC", "SECTION3_TITLE", "SECTION3_DESC",
      "SECTION4_TITLE", "SECTION4_DESC", "CHART1_TITLE", "CHART2_TITLE", "LAGNA_LABEL"
    ];
    howToKeys.forEach(k => { L[`HOWTO_${k}`] = loc.get(`HOW_TO_READ.${k}`, langCode); });

    const rashiKeys = ["ARIES", "TAURUS", "GEMINI", "CANCER", "LEO", "VIRGO", "LIBRA", "SCORPIO", "SAGITTARIUS", "CAPRICORN", "AQUARIUS", "PISCES"];
    rashiKeys.forEach(k => { L[`RASHI_${k}`] = loc.get(`RASHI.${k}`, langCode); });

    const titleHtml = L.vivahamitra + " " + L.horoTitle;

    const LAGNA_TEXT = loc.get('PLANET.LAGNA', langCode);

    // Helper to render South Indian Chart
    const renderChart = (title: string, chartData: HoroscopeV2Chart) => {
      let lagnaSign = 1;
      for (let i = 1; i <= 12; i++) {
        const p = chartData[i.toString()];
        if (p && p.includes(LAGNA_TEXT)) {
          lagnaSign = i;
          break;
        }
      }

      const getTd = (houseStr: string) => {
        const p = chartData[houseStr];
        const isLagna = p && p.includes(LAGNA_TEXT);
        const pFiltered = p ? p.filter(item => item !== LAGNA_TEXT) : [];
        const content = pFiltered.length > 0 ? pFiltered.join("<br>") : "";
        const sign = parseInt(houseStr, 10);
        const houseNo = ((sign - lagnaSign + 12) % 12) + 1;
        return `<td${isLagna ? ' class="lagna-mark"' : ''}><div class="zodiac-bg">${getZodiacIcon(sign)}</div><div class="cell-content">${content}</div><span class="house-no">${houseNo}</span></td>`;
      };

      return `
        <div class="chart-container">
          <table class="chart-table">
            <tr>
              ${getTd("12")}
              ${getTd("1")}
              ${getTd("2")}
              ${getTd("3")}
            </tr>
            <tr>
              ${getTd("11")}
              <td colspan="2" rowspan="2" class="chart-center">${title.replace(/\s*Chart\s*/gi, '')}</td>
              ${getTd("4")}
            </tr>
            <tr>
              ${getTd("10")}
              ${getTd("5")}
            </tr>
            <tr>
              ${getTd("9")}
              ${getTd("8")}
              ${getTd("7")}
              ${getTd("6")}
            </tr>
          </table>
        </div>
      `;
    };

    const renderVisualChart = (title: string, cells: string[]) => {
      return `
        <div class="chart-container" style="width: 100%; max-width: 250px; margin: 15px auto;">
          <div class="chart-title" style="text-align:center; font-weight:bold; font-size:12px; margin-bottom:5px;">${title}</div>
          <table class="chart-table" style="width: 100%; border-collapse: collapse; text-align: center; font-size: 10px; table-layout: fixed;">
            <tr>
              <td style="border: 1px solid #b4366f; height: 60px; width: 25%;">${cells[11]}</td>
              <td style="border: 1px solid #b4366f; height: 60px; width: 25%;">${cells[0]}</td>
              <td style="border: 1px solid #b4366f; height: 60px; width: 25%;">${cells[1]}</td>
              <td style="border: 1px solid #b4366f; height: 60px; width: 25%;">${cells[2]}</td>
            </tr>
            <tr>
              <td style="border: 1px solid #b4366f; height: 60px;">${cells[10]}</td>
              <td colspan="2" rowspan="2" class="chart-center" style="border: 1px solid #b4366f; background: #fffafb;">
                <div style="color:#b4366f; opacity:0.15; font-size:40px;">ॐ</div>
              </td>
              <td style="border: 1px solid #b4366f; height: 60px;">${cells[3]}</td>
            </tr>
            <tr>
              <td style="border: 1px solid #b4366f; height: 60px;">${cells[9]}</td>
              <td style="border: 1px solid #b4366f; height: 60px;">${cells[4]}</td>
            </tr>
            <tr>
              <td style="border: 1px solid #b4366f; height: 60px;">${cells[8]}</td>
              <td style="border: 1px solid #b4366f; height: 60px;">${cells[7]}</td>
              <td style="border: 1px solid #b4366f; height: 60px;">${cells[6]}</td>
              <td style="border: 1px solid #b4366f; height: 60px;">${cells[5]}</td>
            </tr>
          </table>
        </div>
      `;
    };

    return `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+Telugu:wght@400;600;700&family=Noto+Sans+Tamil:wght@400;600;700&family=Noto+Sans+Kannada:wght@400;600;700&family=Noto+Sans+Devanagari:wght@400;600;700&family=Noto+Sans:wght@400;600;700&display=swap" rel="stylesheet">
        <style>
          @page {
            size: A4;
            margin: 12mm;
          }
          body {
            font-family: 'Noto Sans Telugu', 'Noto Sans Tamil', 'Noto Sans Kannada', 'Noto Sans Devanagari', 'Noto Sans', sans-serif;
            font-size: 11pt;
            color: #000;
            line-height: 1.4;
            margin: 0;
            padding: 0;
          }
          .header {
            font-size: 14pt;
            font-weight: bold;
            margin-bottom: 20px;
          }
          .details-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
          }
          .details-table td {
            padding: 4px 5px;
            vertical-align: top;
          }
          .details-table .label {
            width: 40%;
            font-weight: 600;
          }
          .details-table .value {
            width: 60%;
            font-weight: 600;
          }
          .section-title {
            font-size: 12pt;
            font-weight: bold;
            margin: 35px 0 10px 0;
            text-transform: uppercase;
            padding-bottom: 3px;
          }
          .planet-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 25px;
            page-break-inside: avoid;
          }
          .planet-table th {
            border-top: 2px solid #000;
            border-bottom: 2px solid #000;
            text-align: left;
            padding: 6px 4px;
            font-size: 10pt;
          }
          .planet-table td {
            padding: 6px 4px;
            font-size: 10pt;
          }

          .mono {
            font-family: monospace;
            font-size: 11pt;
            letter-spacing: 0.5px;
          }
          .charts-row {
            display: flex;
            justify-content: space-around;
            margin-bottom: 30px;
          }
          .chart-container {
            width: 45%;
            min-width: 320px;
            max-width: 360px;
            margin: 0;
            page-break-inside: avoid;
          }
          .chart-title {
            text-align: center;
            font-size: 12pt;
            font-weight: bold;
            margin-bottom: 8px;
          }
          .chart-table {
            width: 100%;
            table-layout: fixed;
            border-collapse: separate;
            border-spacing: 0;
            border-top: 1px solid #000;
            border-left: 1px solid #000;
          }
          .chart-table td {
            border-bottom: 1px solid #000;
            border-right: 1px solid #000;
            width: 25%;
            height: 75px;
            text-align: center;
            vertical-align: middle;
            font-size: 8pt;
            line-height: 1.2;
            padding: 2px;
            word-break: break-word;
            position: relative;
          }
          .house-no {
            position: absolute;
            bottom: 2px;
            right: 4px;
            font-size: 7pt;
            color: #888;
            z-index: 2;
          }
          .zodiac-bg {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            width: 50px;
            height: 50px;
            opacity: 0.25;
            z-index: 0;
            pointer-events: none;
          }
          .zodiac-bg img {
            width: 100%;
            height: 100%;
            object-fit: contain;
          }
          .cell-content {
            position: relative;
            z-index: 1;
          }
          .chart-center {
            font-size: 11pt !important;
            font-weight: bold;
            color: #333;
          }
          .lagna-mark {
            background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='30' height='30'%3E%3Cline x1='0' y1='16' x2='16' y2='0' stroke='black' stroke-width='1.5'/%3E%3Cline x1='0' y1='22' x2='22' y2='0' stroke='black' stroke-width='1.5'/%3E%3C/svg%3E");
            background-repeat: no-repeat;
            background-position: top left;
          }
          .dasha-balance-box {
            border: 2px solid #000;
            padding: 15px;
            text-align: center;
            margin-bottom: 30px;
            page-break-inside: avoid;
          }
          .dasha-label {
            font-size: 11pt;
            color: #444;
            margin-bottom: 5px;
          }
          .dasha-value {
            font-size: 14pt;
            font-weight: bold;
          }
          .dasha-table {
            width: 100%;
            border-collapse: collapse;
            page-break-inside: auto;
          }
          .dasha-table th, .dasha-table td {
            padding: 4px;
            font-size: 9pt;
            vertical-align: top;
          }
          .dasha-table th {
            border-top: 2px solid #000;
            border-bottom: 2px solid #000;
            text-align: left;
          }
          .mahadasha-group {
            margin-bottom: 15px;
            page-break-inside: avoid;
          }
          .mahadasha-group tr:first-child td {
             border-top: 1px solid #000;
             padding-top: 6px;
          }
          .page-break {
            page-break-before: always;
          }
        </style>
      </head>
      <body>

        <div class="header">${titleHtml}</div>

        <table class="details-table">
          <tr><td class="label">${L.name}</td><td class="value">: ${loc.transliterate(data.birthDetails.name, langCode)}</td></tr>
          <tr><td class="label">${L.gender}</td><td class="value">: ${data.birthDetails.gender}</td></tr>
          <tr><td class="label">${L.gotram}</td><td class="value">: ${loc.transliterate(data.birthDetails.gotram || 'N/A', langCode)}</td></tr>
          <tr><td class="label">${L.dob}</td><td class="value">: ${data.birthDetails.dateOfBirth} ${data.birthDetails.dayOfWeek}</td></tr>
          <tr><td class="label">${L.tob}</td><td class="value">: ${data.birthDetails.timeOfBirth} ${data.birthDetails.standardTime}</td></tr>
          <tr><td class="label">${L.pob}</td><td class="value">: ${loc.transliterate(data.birthDetails.placeOfBirth, langCode)}</td></tr>
          <tr><td class="label">${L.latlon}</td><td class="value">: ${data.birthDetails.longitude}, ${data.birthDetails.latitude}</td></tr>
          <tr><td class="label">${L.timezone}</td><td class="value">: ${data.birthDetails.timezone}</td></tr>
          <tr><td class="label">${L.ayanamsa}</td><td class="value">: ${data.birthDetails.ayanamsa}</td></tr>
          <tr><td class="label">${L.sunrise}</td><td class="value">: ${data.birthDetails.sunrise}</td></tr>
          <tr><td class="label">${L.sunset}</td><td class="value">: ${data.birthDetails.sunset}</td></tr>
          <tr><td class="label">${L.nakshatraPada}</td><td class="value">: ${data.panchanga.nakshatra} - ${data.panchanga.pada}</td></tr>
          <tr><td class="label">${L.rasiLord}</td><td class="value">: ${data.panchanga.rasi} - ${data.panchanga.rasiLord}</td></tr>
          <tr><td class="label">${L.lagnaLord}</td><td class="value">: ${data.panchanga.lagna} - ${data.panchanga.lagnaLord}</td></tr>
          <tr><td class="label">${L.tithi}</td><td class="value">: ${data.panchanga.tithi}</td></tr>
          <tr><td class="label">${L.yoga}</td><td class="value">: ${data.panchanga.yoga}</td></tr>
          <tr><td class="label">${L.karana}</td><td class="value">: ${data.panchanga.karana}</td></tr>
          <tr><td class="label">${L.vara}</td><td class="value">: ${data.panchanga.vara}</td></tr>
        </table>

        <div class="section-title">${L.planetTable}</div>
        <table class="planet-table">
          <tr>
            <th>${L.graha}</th>
            <th>${L.rasi}</th>
            <th>${L.long}</th>
            <th>${L.nakPada}</th>
          </tr>
          ${(() => {
        let rows = "";
        const pt = data.planetaryTable;
        for (let i = 0; i < pt.length; i++) {
          const p1 = pt[i];
          rows += `
                <tr>
                  <td>${p1 ? p1.planet : ''}</td>
                  <td>${p1 ? p1.sign : ''}</td>
                  <td class="mono">${p1 ? p1.formattedLongitude : ''}</td>
                  <td>${p1 ? p1.formattedNakshatra : ''}</td>
                </tr>
              `;
        }
        return rows;
      })()}
        </table>

        <div class="page-break"></div>

        ${(() => {
        const engine = new AstrologyEngine();
        const analysis = engine.analyze(data, langCode);

        if (!analysis) {
          return `<div style="text-align:center; color:red;">Astrological Analysis could not be generated due to insufficient data.</div>`;
        }

        const getChartDesc = (key: string) => {
          if (langCode === 'te') {
            if (key === 'Rasi') return "రాశి చక్రం (D-1) జన్మ సమయంలో గ్రహ స్థితులను, మీ భౌతిక ఉనికిని మరియు సాధారణ జీవిత మార్గాన్ని సూచిస్తుంది.";
            if (key === 'Navamsa') return "నవాంశ చక్రం (D-9) మీ అంతర్గత శక్తిని మరియు ప్రధానంగా వివాహం, జీవిత భాగస్వామి లక్షణాలను తెలియజేస్తుంది.";
            if (key === 'Bhava') return "భావ చక్రం (Chalit) గ్రహాలు ఏ భావంలో ఉన్నాయో ఖచ్చితంగా తెలియజేసి జీవిత సంఘటనలను అంచనా వేస్తుంది.";
          } else if (langCode === 'hi') {
            if (key === 'Rasi') return "राशि चक्र (D-1) जन्म के समय ग्रहों की स्थिति को दर्शाता है जो आपके मुख्य व्यक्तित्व, भौतिक अस्तित्व और सामान्य जीवन पथ को प्रकट करता है।";
            if (key === 'Navamsa') return "नवांश चक्र (D-9) आपके आंतरिक स्वरूप और छिपी हुई क्षमता को प्रकट करता है, और मुख्य रूप से विवाह और जीवनसाथी की विशेषताओं के लिए इसका विश्लेषण किया जाता है।";
            if (key === 'Bhava') return "भाव चक्र (Chalit) 12 भावों में ग्रहों की सटीक स्थिति पर केंद्रित है ताकि विशिष्ट जीवन की घटनाओं की सटीक भविष्यवाणी की जा सके।";
          } else if (langCode === 'ta') {
            if (key === 'Rasi') return "ராசி சக்கரம் (D-1) பிறப்பின் போது கிரக நிலைகளை வரைபடமாக்கி, உங்களின் அடிப்படை ஆளுமை, உடல் இருப்பு மற்றும் பொதுவான வாழ்க்கை பாதையை வெளிப்படுத்துகிறது.";
            if (key === 'Navamsa') return "நவாம்ச சக்கரம் (D-9) உங்களின் உள்நிலை மற்றும் மறைந்திருக்கும் ஆற்றலை வெளிப்படுத்துகிறது, மேலும் இது முக்கியமாக திருமணம் மற்றும் வாழ்க்கைத்துணையின் குணாதிசயங்களுக்காக பகுப்பாய்வு செய்யப்படுகிறது.";
            if (key === 'Bhava') return "பாவ சக்கரம் (Chalit) குறிப்பிட்ட வாழ்க்கை நிகழ்வுகளை துல்லியமாக கணிக்க 12 வீடுகளுக்குள் கிரகங்களின் சரியான இடத்தை மையமாகக் கொண்டுள்ளது.";
          } else if (langCode === 'kn') {
            if (key === 'Rasi') return "ರಾಶಿ ಚಕ್ರವು (D-1) ಹುಟ್ಟಿದ ಸಮಯದಲ್ಲಿ ಗ್ರಹಗಳ ಸ್ಥಾನಗಳನ್ನು ಮ್ಯಾಪ್ ಮಾಡುತ್ತದೆ, ನಿಮ್ಮ ಮೂಲ ವ್ಯಕ್ತಿತ್ವ, ಭೌತಿಕ ಅಸ್ತಿತ್ವ ಮತ್ತು ಸಾಮಾನ್ಯ ಜೀವನ ಮಾರ್ಗವನ್ನು ಬಹಿರಂಗಪಡಿಸುತ್ತದೆ.";
            if (key === 'Navamsa') return "ನವಾಂಶ ಚಕ್ರವು (D-9) ನಿಮ್ಮ ಆಂತರಿಕ ಸ್ವರೂಪ ಮತ್ತು ಗುಪ್ತ ಸಾಮರ್ಥ್ಯವನ್ನು ಬಹಿರಂಗಪಡಿಸುತ್ತದೆ, ಮತ್ತು ಇದನ್ನು ಪ್ರಾಥಮಿಕವಾಗಿ ಮದುವೆ ಮತ್ತು ಸಂಗಾತಿಯ ಗುಣಲಕ್ಷಣಗಳಿಗಾಗಿ ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತದೆ.";
            if (key === 'Bhava') return "ಭಾವ ಚಕ್ರವು (Chalit) ನಿರ್ದಿಷ್ಟ ಜೀವನದ ಘಟನೆಗಳನ್ನು ನಿಖರವಾಗಿ ಊಹಿಸಲು 12 ಮನೆಗಳಲ್ಲಿ ಗ್ರಹಗಳ ನಿಖರವಾದ ಸ್ಥಾನವನ್ನು ಕೇಂದ್ರೀಕರಿಸುತ್ತದೆ.";
          }
          if (key === 'Rasi') return "The Rasi Chart (D-1) maps planetary positions at birth to reveal your core personality, physical existence, and general life path.";
          if (key === 'Navamsa') return "The Navamsa Chart (D-9) reveals your inner self and hidden potential, and is primarily analyzed for marriage and spouse characteristics.";
          if (key === 'Bhava') return "The Bhava Chart (Chalit) focuses on the exact placement of planets within the 12 houses to precisely predict specific life events.";
          return "";
        };

        const getLabel = (key: string) => {
          if (key === 'Confidence') {
            if (langCode === 'te') return 'నమ్మకం';
            if (langCode === 'ta') return 'நம்பிக்கை';
            if (langCode === 'hi') return 'विश्वास';
            if (langCode === 'kn') return 'ವಿಶ್ವಾಸ';
            return 'Confidence';
          }
          if (key === 'BasedOn') {
            if (langCode === 'te') return 'ఆధారంగా';
            if (langCode === 'ta') return 'அடிப்படையில்';
            if (langCode === 'hi') return 'आधार पर';
            if (langCode === 'kn') return 'ಆಧಾರದ ಮೇಲೆ';
            return 'Based on';
          }
          return key;
        };

        const getConfidenceValue = (val: string) => {
          if (val === 'High') {
            if (langCode === 'te') return 'అధిక';
            if (langCode === 'ta') return 'உயர்';
            if (langCode === 'hi') return 'उच्च';
            if (langCode === 'kn') return 'ಹೆಚ್ಚು';
          }
          if (val === 'Moderate') {
            if (langCode === 'te') return 'మధ్యస్థ';
            if (langCode === 'ta') return 'மிதமான';
            if (langCode === 'hi') return 'मध्यम';
            if (langCode === 'kn') return 'ಮಧ್ಯಮ';
          }
          if (val === 'Low') {
            if (langCode === 'te') return 'తక్కువ';
            if (langCode === 'ta') return 'குறைந்த';
            if (langCode === 'hi') return 'निम्न';
            if (langCode === 'kn') return 'ಕಡಿಮೆ';
          }
          return val;
        };

        const renderChartRow = (title: string, chartData: HoroscopeV2Chart, section: any, chartKey: string) => `
            <div style="display: flex; flex-direction: column; align-items: center; justify-content: flex-start; gap: 30px; margin-bottom: 60px; page-break-inside: avoid; width: 100%; box-sizing: border-box;">
              ${renderChart(title, chartData)}
              <div style="width: 100%; max-width: 800px; font-size: 11pt; color: #444; line-height: 1.6; text-align: left; padding: 0 20px; box-sizing: border-box;">
                <div style="font-weight: bold; color: #b4366f; font-size: 14pt; margin-bottom: 12px; border-bottom: 2px solid #b4366f; padding-bottom: 5px; display: inline-block;">
                  ${title.replace(/\s*Chart\s*/gi, '')} ${
                    langCode === 'te' ? 'విశ్లేషణ' :
                    langCode === 'ta' ? 'பகுப்பாய்வு' :
                    langCode === 'hi' ? 'विश्लेषण' :
                    langCode === 'kn' ? 'ವಿಶ್ಲೇಷಣೆ' :
                    'Analysis'
                  }
                </div>
                <div style="margin-bottom: 15px; font-style: italic; color: #666;">${getChartDesc(chartKey)}</div>
                <div>${section.text}</div>
                <div style="margin-top: 20px; padding-top: 15px; border-top: 1px dashed #ddd; font-size: 10pt; color: #555;">
                  <div style="margin-bottom: 8px;"><strong>${getLabel('Confidence')}:</strong> <span style="color: #b4366f;">${getConfidenceValue(section.confidence)}</span></div>
                  <div style="margin-bottom: 4px;"><strong>${getLabel('BasedOn')}:</strong></div>
                  <ul style="margin: 0; padding-left: 22px; color: #666; line-height: 1.5;">
                    ${section.derivedFrom.map((item: string) => `<li>${item}</li>`).join('')}
                  </ul>
                </div>
              </div>
            </div>
          `;

        return `
            <div style="margin: 0 auto 25px auto; width: 96%; padding: 15px; background: #fffafb; border: 2px solid #b4366f; border-radius: 8px; box-sizing: border-box; page-break-inside: avoid;">
              <h3 style="color: #b4366f; margin-top: 0;">${
                langCode === 'te' ? 'చార్ట్ హెల్త్ డాష్‌బోర్డ్' :
                langCode === 'ta' ? 'ஜாதக சுகாதார டாஷ்போர்டு' :
                langCode === 'hi' ? 'चार्ट स्वास्थ्य डैशबोर्ड' :
                langCode === 'kn' ? 'ಚಾರ್ಟ್ ಆರೋಗ್ಯ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್' :
                'Chart Health Dashboard'
              }</h3>
              <div style="display: flex; flex-wrap: wrap; justify-content: space-between; gap: 10px; font-size: 11pt; word-break: break-word;">
                <div style="flex: 1; min-width: 200px;"><strong>${
                  langCode === 'te' ? 'బలమైన విభాగాలు' :
                  langCode === 'ta' ? 'வலுவான பகுதிகள்' :
                  langCode === 'hi' ? 'मजबूत क्षेत्र' :
                  langCode === 'kn' ? 'ಬಲವಾದ ಪ್ರದೇಶಗಳು' :
                  'Strong Areas'
                }:</strong> ${analysis.dashboard.strongAreas.join(", ")}</div>
                <div style="flex: 1; min-width: 200px; text-align: right;"><strong>${
                  langCode === 'te' ? 'అభివృద్ధి చెందుతున్నవి' :
                  langCode === 'ta' ? 'வளரும் பகுதிகள்' :
                  langCode === 'hi' ? 'विकासशील क्षेत्र' :
                  langCode === 'kn' ? 'ಅಭಿವೃದ್ಧಿಶೀಲ ಪ್ರದೇಶಗಳು' :
                  'Developing'
                }:</strong> ${analysis.dashboard.developingAreas.join(", ")}</div>
              </div>
            </div>
            <div style="display: block; width: 100%; margin-top: 20px;">
              ${renderChartRow(L.rasiChart, data.rasiChart, analysis.personality, 'Rasi')}
              ${renderChartRow(L.navamsaChart, data.navamsaChart, analysis.marriage, 'Navamsa')}
              ${renderChartRow(L.bhavaChart, data.bhavaChart, analysis.career, 'Bhava')}
            </div>
          `;
      })()}
        
        <div class="dasha-balance-box">
          <div class="dasha-label">${L.dasaSesham}</div>
          <div class="dasha-value">${data.dashaTable.janmakalaDasaSesham}</div>
        </div>

        <div class="page-break"></div>

        <div class="header">${L.dasaTitle}</div>
        
        <table class="dasha-table">
          <tr>
            <th>${L.dasa}</th>
            <th>${L.bhukti}</th>
            <th>${L.dasaStart}</th>
            <th>${L.dasaEnd}</th>
            <th>${L.dasa}</th>
            <th>${L.bhukti}</th>
            <th>${L.dasaStart}</th>
            <th>${L.dasaEnd}</th>
          </tr>
          ${(() => {
        let rows = "";
        const dashas = data.dashaTable.vimshottari;
        for (let i = 0; i < Math.ceil(dashas.length / 2); i++) {
          const d1 = dashas[i * 2];
          const d2 = dashas[i * 2 + 1];

          let maxBhuktis = Math.max(d1 ? d1.bhuktis.length : 0, d2 ? d2.bhuktis.length : 0);
          rows += `<tbody class="mahadasha-group">`;
          for (let j = 0; j < maxBhuktis; j++) {
            const b1 = d1 && d1.bhuktis[j] ? d1.bhuktis[j] : null;
            const b2 = d2 && d2.bhuktis[j] ? d2.bhuktis[j] : null;

            rows += `
                    <tr>
                      <td>${j === 0 && d1 ? d1.planet : ''}</td>
                      <td>${b1 ? b1.planet : ''}</td>
                      <td>${b1 ? b1.startDate : ''}</td>
                      <td>${b1 ? b1.endDate : ''}</td>
                      
                      <td>${j === 0 && d2 ? d2.planet : ''}</td>
                      <td>${b2 ? b2.planet : ''}</td>
                      <td>${b2 ? b2.startDate : ''}</td>
                      <td>${b2 ? b2.endDate : ''}</td>
                    </tr>
                  `;
          }
          rows += `</tbody>`;
        }
        return rows;
      })()}
        </table>

        <div class="page-break"></div>
        <div class="header" style="color:#b4366f">${L.HOWTO_TITLE}</div>
        <p style="font-size: 13px; color: #555; text-align: center; margin-bottom: 20px;">${L.HOWTO_SUBTITLE}</p>

        <div style="margin-top: 20px;">
          <div style="margin-bottom: 15px;">
            <div style="font-weight: bold; color: #b4366f; font-size: 14px; margin-bottom: 4px;">${L.HOWTO_SECTION1_TITLE}</div>
            <div style="font-size: 13px; color: #333; line-height: 1.5;">${L.HOWTO_SECTION1_DESC}</div>
            ${renderVisualChart(L.HOWTO_CHART1_TITLE, [
        L.RASHI_ARIES, L.RASHI_TAURUS, L.RASHI_GEMINI, L.RASHI_CANCER,
        L.RASHI_LEO, L.RASHI_VIRGO, L.RASHI_LIBRA, L.RASHI_SCORPIO,
        L.RASHI_SAGITTARIUS, L.RASHI_CAPRICORN, L.RASHI_AQUARIUS, L.RASHI_PISCES
      ])}
          </div>
          <div style="margin-bottom: 15px;">
            <div style="font-weight: bold; color: #b4366f; font-size: 14px; margin-bottom: 4px;">${L.HOWTO_SECTION2_TITLE}</div>
            <div style="font-size: 13px; color: #333; line-height: 1.5;">${L.HOWTO_SECTION2_DESC}</div>
            ${renderVisualChart(L.HOWTO_CHART2_TITLE, [
        `1<br><small>(${L.HOWTO_LAGNA_LABEL})</small>`, "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"
      ])}
          </div>
          <div style="margin-bottom: 15px;">
            <div style="font-weight: bold; color: #b4366f; font-size: 14px; margin-bottom: 4px;">${L.HOWTO_SECTION3_TITLE}</div>
            <div style="font-size: 13px; color: #333; line-height: 1.5;">${L.HOWTO_SECTION3_DESC}</div>
          </div>
          <div style="margin-bottom: 15px;">
            <div style="font-weight: bold; color: #b4366f; font-size: 14px; margin-bottom: 4px;">${L.HOWTO_SECTION4_TITLE}</div>
            <div style="font-size: 13px; color: #333; line-height: 1.5;">${L.HOWTO_SECTION4_DESC}</div>
          </div>
        </div>

        <div style="margin-top: 30px; border-top: 1px solid #ddd; padding-top: 20px;">
          <div class="section-title" style="margin-top: 0;">${L.GLOSSARY_TITLE}</div>
          <p style="font-size: 12px; color: #555; margin-bottom: 15px; text-align: center;">${L.GLOSSARY_DESC}</p>
          
          <div style="margin-bottom: 15px;">
            <div style="font-weight: bold; color: #b4366f; font-size: 14px; margin-bottom: 4px;">${L.TITHI_TITLE}</div>
            <div style="font-size: 13px; color: #333; line-height: 1.5;">${L.TITHI_DESC}</div>
          </div>
          <div style="margin-bottom: 15px;">
            <div style="font-weight: bold; color: #b4366f; font-size: 14px; margin-bottom: 4px;">${L.VARA_TITLE}</div>
            <div style="font-size: 13px; color: #333; line-height: 1.5;">${L.VARA_DESC}</div>
          </div>
          <div style="margin-bottom: 15px;">
            <div style="font-weight: bold; color: #b4366f; font-size: 14px; margin-bottom: 4px;">${L.NAKSHATRA_TITLE}</div>
            <div style="font-size: 13px; color: #333; line-height: 1.5;">${L.NAKSHATRA_DESC}</div>
          </div>
          <div style="margin-bottom: 15px;">
            <div style="font-weight: bold; color: #b4366f; font-size: 14px; margin-bottom: 4px;">${L.YOGA_TITLE}</div>
            <div style="font-size: 13px; color: #333; line-height: 1.5;">${L.YOGA_DESC}</div>
          </div>
          <div style="margin-bottom: 15px;">
            <div style="font-weight: bold; color: #b4366f; font-size: 14px; margin-bottom: 4px;">${L.KARANA_TITLE}</div>
            <div style="font-size: 13px; color: #333; line-height: 1.5;">${L.KARANA_DESC}</div>
          </div>
          <div style="margin-bottom: 15px;">
            <div style="font-weight: bold; color: #b4366f; font-size: 14px; margin-bottom: 4px;">${L.LAGNA_TITLE}</div>
            <div style="font-size: 13px; color: #333; line-height: 1.5;">${L.LAGNA_DESC}</div>
          </div>
          <div style="margin-bottom: 15px;">
            <div style="font-weight: bold; color: #b4366f; font-size: 14px; margin-bottom: 4px;">${L.RASI_TITLE}</div>
            <div style="font-size: 13px; color: #333; line-height: 1.5;">${L.RASI_DESC}</div>
          </div>
        </div>

      </body>
      </html>
    `;
  }
}
