export type LanguageCode = "en" | "te" | "hi" | "ta" | "kn";

export const REPORT_LABELS = {
  en: {
    reportTitle: "Horoscope Matching Report",
    brideDetails: "Bride Details",
    groomDetails: "Groom Details",
    birthDetails: "Birth Details",
    dateOfBirth: "Date of Birth",
    timeOfBirth: "Time of Birth",
    placeOfBirth: "Coordinates",
    nakshatra: "Nakshatra",
    rashi: "Rashi (Moon Sign)",
    lagna: "Lagna (Ascendant)",
    compatibilitySummary: "Compatibility Summary",
    totalScore: "Total Score",
    outOf: "out of 36",
    ashtakootaMatching: "Ashtakoota Matching",
    koota: "Koota",
    max: "Max",
    obtained: "Obtained",
    status: "Status",
    doshaAnalysis: "Dosha Analysis",
    manglikStatus: "Manglik Status",
    present: "Present",
    notPresent: "Not Present",
    compatibilityAnalysis: "Compatibility Analysis",
    emotionalCompatibility: "Emotional Compatibility (Vashya)",
    communicationCompatibility: "Communication & Harmony (Graha Maitri)",
    familyCompatibility: "Family & Temperament (Gana)",
    financialCompatibility: "Prosperity & Wealth (Tara & Varna)",
    physicalCompatibility: "Physical & Intimate Harmony (Yoni)",
    strengths: "Relationship Strengths",
    challenges: "Areas Requiring Attention",
    remedies: "Suggested Remedies",
    executiveSummary: "Executive Summary",
    finalRecommendation: "Final Recommendation",
    excellent: "Excellent Compatibility",
    veryGood: "Very Good Match",
    good: "Good Compatibility",
    average: "Average Compatibility",
    needsCare: "Needs Care",
    lowCompatibility: "Low Compatibility",
    missingDataMessage: "This analysis could not be completed because the required information was not provided by the API.",
    noRemedies: "No specific remedies were provided in the analysis.",
    noRemediesProvided: "No remedies were provided by the API.",
    footerText: "Vivahamitra Professional Report"
  },
  te: {
    reportTitle: "జాతక పొంతన నివేదిక",
    brideDetails: "వధువు వివరాలు",
    groomDetails: "వరుడి వివరాలు",
    birthDetails: "జనన వివరాలు",
    dateOfBirth: "పుట్టిన తేది",
    timeOfBirth: "పుట్టిన సమయం",
    placeOfBirth: "స్థానం",
    nakshatra: "నక్షత్రం",
    rashi: "రాశి",
    lagna: "లగ్నం",
    compatibilitySummary: "పొంతన సారాంశం",
    totalScore: "మొత్తం స్కోరు",
    outOf: "36 కి",
    ashtakootaMatching: "అష్టకూట పొంతన",
    koota: "కూట",
    max: "గరిష్ట",
    obtained: "సాధించినది",
    status: "స్థితి",
    doshaAnalysis: "దోష విశ్లేషణ",
    manglikStatus: "మాంగలిక స్థితి",
    present: "ఉంది",
    notPresent: "లేదు",
    compatibilityAnalysis: "పొంతన విశ్లేషణ",
    emotionalCompatibility: "మానసిక అనుకూలత (వశ్య)",
    communicationCompatibility: "భావప్రకటన & సామరస్యం (గ్రహ మైత్రి)",
    familyCompatibility: "కుటుంబం & స్వభావం (గణ)",
    financialCompatibility: "ఆర్థిక అనుకూలత (తార & వర్ణ)",
    physicalCompatibility: "శారీరక అనుకూలత (యోని)",
    strengths: "బలాలు",
    challenges: "సవాళ్లు",
    remedies: "సూచించిన పరిహారాలు",
    executiveSummary: "సారాంశం",
    finalRecommendation: "తుది సిఫార్సు",
    excellent: "అద్భుతం",
    veryGood: "చాలా బాగుంది",
    good: "బాగుంది",
    average: "సాధారణం",
    needsCare: "శ్రద్ధ అవసరం",
    lowCompatibility: "తక్కువ అనుకూలత",
    missingDataMessage: "API నుండి అవసరమైన డేటా అందుబాటులో లేనందున ఈ విశ్లేషణ పూర్తి కాలేదు.",
    noRemedies: "విశ్లేషణలో నిర్దిష్ట పరిహారాలు సూచించబడలేదు."
  },
  hi: {
    reportTitle: "कुंडली मिलान रिपोर्ट",
    brideDetails: "वधू का विवरण",
    groomDetails: "वर का विवरण",
    birthDetails: "जन्म विवरण",
    dateOfBirth: "जन्म तिथि",
    timeOfBirth: "जन्म समय",
    placeOfBirth: "स्थान",
    nakshatra: "नक्षत्र",
    rashi: "राशि",
    lagna: "लग्न",
    compatibilitySummary: "अनुकूलता सारांश",
    totalScore: "कुल अंक",
    outOf: "36 में से",
    ashtakootaMatching: "अष्टकूट मिलान",
    koota: "कूट",
    max: "अधिकतम",
    obtained: "प्राप्त",
    status: "स्थिति",
    doshaAnalysis: "दोष विश्लेषण",
    manglikStatus: "मांगलिक स्थिति",
    present: "उपस्थित",
    notPresent: "अनुपस्थित",
    compatibilityAnalysis: "अनुकूलता विश्लेषण",
    emotionalCompatibility: "भावनात्मक अनुकूलता (वश्य)",
    communicationCompatibility: "संचार और सद्भाव (ग्रह मैत्री)",
    familyCompatibility: "परिवार और स्वभाव (गण)",
    financialCompatibility: "समृद्धि और धन (तारा और वर्ण)",
    physicalCompatibility: "शारीरिक और अंतरंग सद्भाव (योनि)",
    strengths: "प्रमुख ताकतें",
    challenges: "चुनौतियां",
    remedies: "सुझाए गए उपाय",
    executiveSummary: "कार्यकारी सारांश",
    finalRecommendation: "अंतिम सिफारिश",
    excellent: "उत्कृष्ट",
    veryGood: "बहुत अच्छा",
    good: "अच्छा",
    average: "औसत",
    needsCare: "ध्यान देने योग्य",
    lowCompatibility: "कम अनुकूलता",
    missingDataMessage: "यह विश्लेषण पूरा नहीं किया जा सका क्योंकि API से आवश्यक डेटा उपलब्ध नहीं था।",
    noRemedies: "विश्लेषण में कोई विशिष्ट उपाय प्रदान नहीं किए गए थे।"
  },
  ta: {
    reportTitle: "ஜாதக பொருத்தம் அறிக்கை",
    brideDetails: "மணமகள் விவரங்கள்",
    groomDetails: "மணமகன் விவரங்கள்",
    birthDetails: "பிறப்பு விவரங்கள்",
    dateOfBirth: "பிறந்த தேதி",
    timeOfBirth: "பிறந்த நேரம்",
    placeOfBirth: "இடம்",
    nakshatra: "நட்சத்திரம்",
    rashi: "ராசி",
    lagna: "லக்னம்",
    compatibilitySummary: "பொருத்த சுருக்கம்",
    totalScore: "மொத்த மதிப்பெண்",
    outOf: "36 க்கு",
    ashtakootaMatching: "அஷ்டகூட பொருத்தம்",
    koota: "கூட",
    max: "அதிகபட்ச",
    obtained: "பெற்றது",
    status: "நிலை",
    doshaAnalysis: "தோஷ பகுப்பாய்வு",
    manglikStatus: "மாங்கல்ய நிலை",
    present: "உள்ளது",
    notPresent: "இல்லை",
    compatibilityAnalysis: "பொருத்த பகுப்பாய்வு",
    emotionalCompatibility: "உணர்ச்சி பொருத்தம் (வஸ்ய)",
    communicationCompatibility: "தொடர்பு & நல்லிணக்கம் (கிரக மைத்ரி)",
    familyCompatibility: "குடும்பம் & இயல்பு (கண)",
    financialCompatibility: "நிதி பொருத்தம் (தாரா & வர்ண)",
    physicalCompatibility: "உடல் பொருத்தம் (யோனி)",
    strengths: "பலங்கள்",
    challenges: "சவால்கள்",
    remedies: "பரிந்துரைக்கப்பட்ட பரிகாரங்கள்",
    executiveSummary: "சுருக்கம்",
    finalRecommendation: "இறுதி பரிந்துரை",
    excellent: "மிக நன்று",
    veryGood: "மிகவும் நன்று",
    good: "நன்று",
    average: "சராசரி",
    needsCare: "கவனம் தேவை",
    lowCompatibility: "குறைந்த பொருத்தம்",
    missingDataMessage: "API இலிருந்து தேவையான தரவு கிடைக்காததால் இந்தப் பகுப்பாய்வை முடிக்க முடியவில்லை.",
    noRemedies: "பகுப்பாய்வில் குறிப்பிட்ட பரிகாரங்கள் எதுவும் வழங்கப்படவில்லை."
  },
  kn: {
    reportTitle: "ಜಾತಕ ಹೊಂದಾಣಿಕೆ ವರದಿ",
    brideDetails: "ವಧುವಿನ ವಿವರಗಳು",
    groomDetails: "ವರನ ವಿವರಗಳು",
    birthDetails: "ಜನನ ವಿವರಗಳು",
    dateOfBirth: "ಹುಟ್ಟಿದ ದಿನಾಂಕ",
    timeOfBirth: "ಹುಟ್ಟಿದ ಸಮಯ",
    placeOfBirth: "ಸ್ಥಳ",
    nakshatra: "ನಕ್ಷತ್ರ",
    rashi: "ರಾಶಿ",
    lagna: "ಲಗ್ನ",
    compatibilitySummary: "ಹೊಂದಾಣಿಕೆ ಸಾರಾಂಶ",
    totalScore: "ಒಟ್ಟು ಅಂಕಗಳು",
    outOf: "36 ಕ್ಕೆ",
    ashtakootaMatching: "ಅಷ್ಟಕೂಟ ಹೊಂದಾಣಿಕೆ",
    koota: "ಕೂಟ",
    max: "ಗರಿಷ್ಠ",
    obtained: "ಪಡೆದದ್ದು",
    status: "ಸ್ಥಿತಿ",
    doshaAnalysis: "ದೋಷ ವಿಶ್ಲೇಷಣೆ",
    manglikStatus: "ಮಾಂಗಲಿಕ ಸ್ಥಿತಿ",
    present: "ಇದೆ",
    notPresent: "ಇಲ್ಲ",
    compatibilityAnalysis: "ಹೊಂದಾಣಿಕೆ ವಿಶ್ಲೇಷಣೆ",
    emotionalCompatibility: "ಭಾವನಾತ್ಮಕ ಹೊಂದಾಣಿಕೆ (ವಶ್ಯ)",
    communicationCompatibility: "ಸಂವಹನ ಮತ್ತು ಸಾಮರಸ್ಯ (ಗ್ರಹ ಮೈತ್ರಿ)",
    familyCompatibility: "ಕುಟುಂಬ ಮತ್ತು ಸ್ವಭಾವ (ಗಣ)",
    financialCompatibility: "ಆರ್ಥಿಕ ಹೊಂದಾಣಿಕೆ (ತಾರಾ ಮತ್ತು ವರ್ಣ)",
    physicalCompatibility: "ದೈಹಿಕ ಹೊಂದಾಣಿಕೆ (ಯೋನಿ)",
    strengths: "ಬಲಗಳು",
    challenges: "ಸವಾಲುಗಳು",
    remedies: "ಸೂಚಿಸಲಾದ ಪರಿಹಾರಗಳು",
    executiveSummary: "ಕಾರ್ಯನಿರ್ವಾಹಕ ಸಾರಾಂಶ",
    finalRecommendation: "ಅಂತಿಮ ಶಿಫಾರಸು",
    excellent: "ಅತ್ಯುತ್ತಮ",
    veryGood: "ತುಂಬಾ ಒಳ್ಳೆಯದು",
    good: "ಒಳ್ಳೆಯದು",
    average: "ಸಾಧಾರಣ",
    needsCare: "ಗಮನ ಹರಿಸಬೇಕು",
    lowCompatibility: "ಕಡಿಮೆ ಹೊಂದಾಣಿಕೆ",
    missingDataMessage: "API ನಿಂದ ಅಗತ್ಯ ಡೇಟಾ ಲಭ್ಯವಿಲ್ಲದ ಕಾರಣ ಈ ವಿಶ್ಲೇಷಣೆಯನ್ನು ಪೂರ್ಣಗೊಳಿಸಲಾಗಲಿಲ್ಲ.",
    noRemedies: "ವಿಶ್ಲೇಷಣೆಯಲ್ಲಿ ಯಾವುದೇ ನಿರ್ದಿಷ್ಟ ಪರಿಹಾರಗಳನ್ನು ಒದಗಿಸಲಾಗಿಲ್ಲ."
  }
};

export const getReportString = (lang: string, key: keyof typeof REPORT_LABELS["en"]): string => {
  const language = (lang as LanguageCode) || "en";
  return REPORT_LABELS[language]?.[key] || REPORT_LABELS["en"][key];
};
